import { PrismaClient } from "@prisma/client";
import type { FastifyInstance } from "fastify";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { buildApp } from "../src/app.js";
import type { Config } from "../src/config.js";
import type { RedisService } from "../src/lib/redis.js";

const databaseUrl = process.env.TEST_DATABASE_URL ?? process.env.DATABASE_URL;
const run = databaseUrl ? describe : describe.skip;
run("security integration", () => {
  const prisma = new PrismaClient({ datasourceUrl: databaseUrl }); let app: FastifyInstance; const objects = new Map<string,{size:bigint;type:string}>();
  const config:Config={NODE_ENV:"test",DATABASE_URL:databaseUrl!,REDIS_URL:"redis://localhost:6379",CACHE_TTL_SECONDS:60,AWS_ACCESS_KEY_ID:"test",AWS_SECRET_ACCESS_KEY:"test",AWS_REGION:"us-east-1",AWS_S3_BUCKET:"private-test",AUTH_SECRET:"a".repeat(32),FRONTEND_ORIGIN:"http://localhost:3000",PORT:4000,DEFAULT_STORAGE_LIMIT_BYTES:1000n,MAX_FILE_SIZE_BYTES:1000n,PRESIGNED_URL_TTL_SECONDS:600,SESSION_TTL_DAYS:30,UPLOAD_LOCK_TTL_MS:10000};
  const s3={uploadUrl:async(key:string,type:string)=>{objects.set(key,{size:0n,type});return `https://upload.test/${key}`},downloadUrl:async(key:string)=>`https://download.test/${key}`,head:async(key:string)=>{const o=objects.get(key);if(!o)throw new Error();return{ContentLength:Number(o.size),ContentType:o.type,$metadata:{}}},remove:async(key:string)=>{if(!objects.has(key))throw new Error();objects.delete(key)}};
  const cache=new Map<string,string>();
  const redis:RedisService={getJson:async<T>(key:string)=>cache.has(key)?JSON.parse(cache.get(key)!) as T:null,setJson:async(key,value)=>{cache.set(key,JSON.stringify(value))},del:async(...keys)=>{keys.forEach(key=>cache.delete(key))},withLock:async(_key,_ttl,task)=>task(),close:async()=>undefined};
  beforeAll(async()=>{app=await buildApp({config,prisma,s3,redis});await app.ready();await prisma.uploadIntent.deleteMany();await prisma.session.deleteMany();await prisma.file.deleteMany();await prisma.folder.deleteMany();await prisma.user.deleteMany()});
  afterAll(async()=>{await app.close();await prisma.$disconnect()});
  const register=async(email:string)=>{const response=await app.inject({method:"POST",url:"/api/auth/register",headers:{origin:config.FRONTEND_ORIGIN},payload:{name:"Test User",email,password:"SecurePass1!",confirmPassword:"SecurePass1!"}});return{response,cookie:response.cookies[0]?.value,header:`selfcloud_session=${response.cookies[0]?.value}`}};
  it("registers a user and creates a root folder",async()=>{const {response}=await register("register@example.com");expect(response.statusCode).toBe(201);const user=await prisma.user.findUniqueOrThrow({where:{email:"register@example.com"},include:{folders:true}});expect(user.passwordHash).not.toContain("SecurePass1!");expect(user.folders.some(f=>f.isRoot)).toBe(true);expect(response.body).not.toContain("passwordHash")});
  it("logs in with a secure session cookie",async()=>{await register("login@example.com");const r=await app.inject({method:"POST",url:"/api/auth/login",headers:{origin:config.FRONTEND_ORIGIN},payload:{email:"login@example.com",password:"SecurePass1!"}});expect(r.statusCode).toBe(200);expect(r.headers["set-cookie"]).toContain("HttpOnly")});
  it("rejects unauthorized dashboard data access",async()=>{expect((await app.inject({method:"GET",url:"/api/storage"})).statusCode).toBe(401)});
  it("requires authorization before issuing upload URLs",async()=>{const r=await app.inject({method:"POST",url:"/api/files/upload-url",headers:{origin:config.FRONTEND_ORIGIN},payload:{filename:"a.pdf",size:2,mimeType:"application/pdf",folderId:"cm1234567890123456789012"}});expect(r.statusCode).toBe(401)});
  it("enforces the storage limit",async()=>{const u=await register("quota@example.com");const root=await prisma.folder.findFirstOrThrow({where:{user:{email:"quota@example.com"},isRoot:true}});const r=await app.inject({method:"POST",url:"/api/files/upload-url",headers:{cookie:u.header,origin:config.FRONTEND_ORIGIN},payload:{filename:"large.pdf",size:1001,mimeType:"application/pdf",folderId:root.id}});expect(r.statusCode).toBe(413)});
  async function completedFile(email:string,name:string,size=10){const u=await register(email);const user=await prisma.user.findUniqueOrThrow({where:{email}});const root=await prisma.folder.findFirstOrThrow({where:{userId:user.id,isRoot:true}});const init=await app.inject({method:"POST",url:"/api/files/upload-url",headers:{cookie:u.header,origin:config.FRONTEND_ORIGIN},payload:{filename:name,size,mimeType:"application/pdf",folderId:root.id}});const uploadId=init.json().uploadId;const intent=await prisma.uploadIntent.findUniqueOrThrow({where:{id:uploadId}});objects.set(intent.s3Key,{size:BigInt(size),type:"application/pdf"});const done=await app.inject({method:"POST",url:"/api/files/complete",headers:{cookie:u.header,origin:config.FRONTEND_ORIGIN},payload:{uploadId}});return{...u,user,root,file:done.json().file}}
  it("lists only the current user's files",async()=>{const a=await completedFile("list-a@example.com","mine.pdf");await completedFile("list-b@example.com","theirs.pdf");const r=await app.inject({method:"GET",url:`/api/files?folderId=${a.root.id}`,headers:{cookie:a.header}});expect(r.json().files.map((f:{originalName:string})=>f.originalName)).toEqual(["mine.pdf"])});
  it("cannot download another user's file",async()=>{const owner=await completedFile("down-owner@example.com","private.pdf");const other=await register("down-other@example.com");expect((await app.inject({method:"GET",url:`/api/files/${owner.file.id}/download`,headers:{cookie:other.header}})).statusCode).toBe(404)});
  it("cannot delete another user's file",async()=>{const owner=await completedFile("delete-owner@example.com","private.pdf");const other=await register("delete-other@example.com");expect((await app.inject({method:"DELETE",url:`/api/files/${owner.file.id}`,headers:{cookie:other.header,origin:config.FRONTEND_ORIGIN}})).statusCode).toBe(404);expect(await prisma.file.findUnique({where:{id:owner.file.id}})).not.toBeNull()});
  it("increments storage only after verified completion",async()=>{const done=await completedFile("usage-up@example.com","file.pdf",75);const user=await prisma.user.findUniqueOrThrow({where:{id:done.user.id}});expect(user.storageUsed).toBe(75n);expect(user.storageReserved).toBe(0n)});
  it("decrements storage after S3 and metadata deletion",async()=>{const done=await completedFile("usage-down@example.com","file.pdf",80);const r=await app.inject({method:"DELETE",url:`/api/files/${done.file.id}`,headers:{cookie:done.header,origin:config.FRONTEND_ORIGIN}});expect(r.statusCode).toBe(204);expect((await prisma.user.findUniqueOrThrow({where:{id:done.user.id}})).storageUsed).toBe(0n)});
});
