import { randomUUID } from "node:crypto";
import { mkdtemp, rm, readFile, symlink, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Readable } from "node:stream";
import { beforeEach, afterEach, expect, it } from "vitest";
import { createLocalStorage, type LocalStorage } from "../src/lib/storage.js";
import { loadConfig } from "../src/config.js";
let root: string;
let storage: LocalStorage;
beforeEach(async()=>{root=await mkdtemp(join(tmpdir(),"secure-cloud-"));storage=await createLocalStorage(root)});
afterEach(async()=>{await rm(root,{recursive:true,force:true})});
it("writes exact bytes privately, reads and permanently deletes",async()=>{const key=randomUUID();await storage.write(key,Readable.from([Buffer.from("hello")]),5n);expect(await readFile(join(root,key),"utf8")).toBe("hello");expect((await stat(join(root,key))).mode & 0o777).toBe(0o600);const stream=await storage.read(key);const chunks=[];for await(const chunk of stream)chunks.push(chunk);expect(Buffer.concat(chunks).toString()).toBe("hello");await storage.remove(key);await storage.remove(key);await expect(storage.read(key)).rejects.toMatchObject({statusCode:404})});
it.each(["../secret","/etc/passwd","a/b","..\\secret",""])("rejects unsafe key %s",async key=>{await expect(storage.read(key)).rejects.toMatchObject({code:"INVALID_STORAGE_KEY"});await expect(storage.write(key,Readable.from([]),0n)).rejects.toMatchObject({code:"INVALID_STORAGE_KEY"});await expect(storage.remove(key)).rejects.toMatchObject({code:"INVALID_STORAGE_KEY"})});
it.each([2n,10n])("cleans up mismatched size %s",async size=>{const key=randomUUID();await expect(storage.write(key,Readable.from([Buffer.from("hello")]),size)).rejects.toBeDefined();await expect(stat(join(root,key))).rejects.toMatchObject({code:"ENOENT"})});
it("accepts empty files",async()=>{const key=randomUUID();await storage.write(key,Readable.from([]),0n);expect((await stat(join(root,key))).size).toBe(0)});
it("does not overwrite existing files or follow symlinks",async()=>{const key=randomUUID();await storage.write(key,Readable.from(["a"]),1n);await expect(storage.write(key,Readable.from(["b"]),1n)).rejects.toMatchObject({code:"EEXIST"});expect(await readFile(join(root,key),"utf8")).toBe("a");const link=randomUUID();await symlink(join(root,key),join(root,link));await expect(storage.read(link)).rejects.toMatchObject({code:"ELOOP"})});
it("cleans up an interrupted source",async()=>{const key=randomUUID();const source=Readable.from((async function*(){yield Buffer.from("a");throw new Error("disconnect")})());await expect(storage.write(key,source,2n)).rejects.toThrow("disconnect");await expect(stat(join(root,key))).rejects.toMatchObject({code:"ENOENT"})});
it("defaults to the required server path and rejects a different quota",()=>{const env={DATABASE_URL:"postgresql://localhost/test",AUTH_SECRET:"a".repeat(32)};expect(loadConfig(env).STORAGE_PATH).toBe("/srv/secure-cloud-storage");expect(loadConfig(env).STORAGE_LIMIT_BYTES).toBe(5368709120n);expect(()=>loadConfig({...env,STORAGE_LIMIT_BYTES:"10737418240"})).toThrow()});
