"use client";
import { Cloud, Files, FolderClosed, Gauge, LogOut, Menu, Moon, Settings, Sun, Trash2, X } from "lucide-react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";

const links = [{ href: "/dashboard", label: "Dashboard", icon: Gauge }, { href: "/files", label: "My files", icon: Files }, { href: "/files?folders=true", label: "Folders", icon: FolderClosed }, { href: "/trash", label: "Trash", icon: Trash2 }, { href: "/settings", label: "Settings", icon: Settings }];
export function AppShell({ children }: { children: React.ReactNode }) {
  const path = usePathname(); const router = useRouter(); const [open, setOpen] = useState(false); const [dark, setDark] = useState(false); const [user, setUser] = useState<{name:string;email:string}|null>(null);
  useEffect(() => { const stored = localStorage.getItem("theme") === "dark"; setDark(stored); document.documentElement.classList.toggle("dark", stored); api<{user:{name:string;email:string}}>("/auth/me").then(r => setUser(r.user)).catch(() => router.replace("/login")); }, [router]);
  function toggleTheme() { const next = !dark; setDark(next); document.documentElement.classList.toggle("dark", next); localStorage.setItem("theme", next ? "dark" : "light"); }
  async function logout() { await api("/auth/logout", { method: "POST" }); router.replace("/login"); }
  const sidebar = <aside className="flex h-full w-[250px] flex-col border-r border-[var(--line)] bg-[var(--panel)] p-4"><div className="mb-8 flex items-center justify-between"><Link href="/dashboard" className="flex items-center gap-3 text-lg font-bold"><span className="grid size-9 place-items-center rounded-md bg-emerald-700 text-white"><Cloud size={21}/></span>Self Cloud</Link><button className="md:hidden" onClick={() => setOpen(false)} aria-label="Close navigation"><X/></button></div><nav className="space-y-1">{links.map(({href,label,icon:Icon}) => <Link key={label} href={href} onClick={() => setOpen(false)} className={`flex h-11 items-center gap-3 rounded-md px-3 text-sm font-medium ${path === href.split("?")[0] ? "bg-emerald-700 text-white" : "text-[var(--muted)] hover:bg-[var(--bg)] hover:text-[var(--ink)]"}`}><Icon size={19}/>{label}</Link>)}</nav><div className="mt-auto border-t border-[var(--line)] pt-4"><div className="mb-3 truncate px-2"><p className="truncate text-sm font-semibold">{user?.name ?? "Loading..."}</p><p className="truncate text-xs text-[var(--muted)]">{user?.email}</p></div><button onClick={logout} className="flex h-10 w-full items-center gap-3 rounded-md px-2 text-sm text-[var(--muted)] hover:bg-[var(--bg)]"><LogOut size={18}/>Sign out</button></div></aside>;
  return <div className="flex min-h-screen"><div className="hidden md:block">{sidebar}</div>{open && <div className="fixed inset-0 z-40 md:hidden"><button className="absolute inset-0 bg-black/40" onClick={() => setOpen(false)} aria-label="Close navigation"/>{sidebar}</div>}<div className="min-w-0 flex-1"><header className="flex h-16 items-center justify-between border-b border-[var(--line)] bg-[var(--panel)] px-4 md:px-7"><button className="md:hidden" onClick={() => setOpen(true)} aria-label="Open navigation"><Menu/></button><span className="hidden text-sm font-medium md:block">Private workspace</span><button onClick={toggleTheme} className="grid size-10 place-items-center rounded-md border border-[var(--line)]" aria-label="Toggle color theme">{dark ? <Sun size={19}/> : <Moon size={19}/>}</button></header><main className="p-4 md:p-7">{children}</main></div></div>;
}
