"use client";
import { Archive, ChevronLeft, ChevronRight, Download, File as FileIcon, FileText, Folder, FolderPlus, Grid2X2, Image as ImageIcon, List, Loader2, MoreVertical, Music, Search, Trash2, Upload, Video, X } from "lucide-react";
import Link from "next/link";
import { ChangeEvent, DragEvent, useCallback, useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import { api, formatBytes, uploadToS3 } from "@/lib/api";

type CloudFile={id:string;originalName:string;mimeType:string;size:string;createdAt:string;folder:{id:string;name:string}};
type CloudFolder={id:string;name:string;parentId:string|null;isRoot:boolean};
type Uploading={name:string;progress:number};
export function FileManager({dashboard=false}:{dashboard?:boolean}){
 const input=useRef<HTMLInputElement>(null); const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const [files,setFiles]=useState<CloudFile[]>([]),[folders,setFolders]=useState<CloudFolder[]>([]),[folderId,setFolderId]=useState(""),[loading,setLoading]=useState(true),[view,setView]=useState<"list"|"grid">("list"),[search,setSearch]=useState(""),[query,setQuery]=useState(""),[type,setType]=useState("all"),[sort,setSort]=useState("createdAt"),[page,setPage]=useState(1),[pages,setPages]=useState(1),[drag,setDrag]=useState(false),[uploading,setUploading]=useState<Uploading[]>([]),[deleting,setDeleting]=useState<CloudFile|null>(null),[newFolder,setNewFolder]=useState(false);
 const loadFolders=useCallback(async()=>{const r=await api<{folders:CloudFolder[]}>("/folders");setFolders(r.folders);if(!folderId){const root=r.folders.find(f=>f.isRoot);if(root)setFolderId(root.id)}},[folderId]);
 const loadFiles=useCallback(async()=>{if(!folderId)return;setLoading(true);try{const p=new URLSearchParams({folderId,search:query,type,sort,order:sort==="name"?"asc":"desc",page:String(page),limit:dashboard?"6":"30"});const r=await api<{files:CloudFile[];pagination:{pages:number}}>(`/files?${p}`);setFiles(r.files);setPages(r.pagination.pages||1)}finally{setLoading(false)}},[folderId,query,type,sort,page,dashboard]);
 useEffect(()=>{loadFolders().catch(e=>toast.error(e.message))},[loadFolders]); useEffect(()=>{loadFiles().catch(e=>toast.error(e.message))},[loadFiles]);
 useEffect(()=>{if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>{setQuery(search);setPage(1)},300);return()=>{if(timer.current)clearTimeout(timer.current)}},[search]);
 async function upload(list:FileList|File[]){if(!folderId)return;for(const file of Array.from(list)){const mime=file.type||"application/octet-stream";setUploading(v=>[...v,{name:file.name,progress:0}]);try{const r=await api<{uploadId:string;uploadUrl:string}>("/files/upload-url",{method:"POST",body:JSON.stringify({filename:file.name,size:file.size,mimeType:mime,folderId})});await uploadToS3(r.uploadUrl,file,p=>setUploading(v=>v.map(x=>x.name===file.name?{...x,progress:p}:x)));await api("/files/complete",{method:"POST",body:JSON.stringify({uploadId:r.uploadId})});toast.success(`${file.name} uploaded`)}catch(e){toast.error(e instanceof Error?e.message:"Upload failed")}finally{setUploading(v=>v.filter(x=>x.name!==file.name))}}loadFiles()}
 async function download(file:CloudFile){try{const r=await api<{url:string}>(`/files/${file.id}/download`);window.location.assign(r.url)}catch(e){toast.error(e instanceof Error?e.message:"Download failed")}}
 async function remove(){if(!deleting)return;try{await api(`/files/${deleting.id}`,{method:"DELETE"});toast.success("File deleted");setDeleting(null);loadFiles()}catch(e){toast.error(e instanceof Error?e.message:"Delete failed")}}
 async function createFolder(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);try{await api("/folders",{method:"POST",body:JSON.stringify({name:fd.get("name"),parentId:folderId})});setNewFolder(false);loadFolders();toast.success("Folder created")}catch(e){toast.error(e instanceof Error?e.message:"Could not create folder")}}
 function drop(e:DragEvent){e.preventDefault();setDrag(false);if(e.dataTransfer.files.length)upload(e.dataTransfer.files)}
 const visibleFolders=folders.filter(f=>f.parentId===folderId);
 return <section onDragEnter={e=>{e.preventDefault();setDrag(true)}} onDragOver={e=>e.preventDefault()} onDrop={drop}>
  <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-[var(--muted)]">{dashboard?"Recent activity":"File manager"}</p><h1 className={`${dashboard?"text-2xl":"text-3xl"} mt-1 font-semibold`}>{folders.find(f=>f.id===folderId)?.name??"My files"}</h1></div><div className="flex gap-2"><button onClick={()=>setNewFolder(true)} className="focus-ring flex h-10 items-center gap-2 rounded-md border border-[var(--line)] bg-[var(--panel)] px-3 text-sm font-medium"><FolderPlus size={18}/>New folder</button><button onClick={()=>input.current?.click()} className="focus-ring flex h-10 items-center gap-2 rounded-md bg-emerald-700 px-4 text-sm font-semibold text-white"><Upload size={18}/>Upload</button><input ref={input} hidden type="file" multiple onChange={(e:ChangeEvent<HTMLInputElement>)=>e.target.files&&upload(e.target.files)}/></div></div>
  {!dashboard&&<div className="mt-6 flex flex-wrap gap-3 border-y border-[var(--line)] py-4"><label className="relative min-w-[220px] flex-1"><Search className="absolute left-3 top-2.5 text-[var(--muted)]" size={19}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search files" className="focus-ring h-10 w-full rounded-md border border-[var(--line)] bg-[var(--panel)] pl-10 pr-3"/></label><select aria-label="File type" value={type} onChange={e=>{setType(e.target.value);setPage(1)}} className="h-10 rounded-md border border-[var(--line)] bg-[var(--panel)] px-3"><option value="all">All types</option><option value="image">Images</option><option value="video">Videos</option><option value="audio">Audio</option><option value="document">Documents</option><option value="archive">Archives</option></select><select aria-label="Sort files" value={sort} onChange={e=>setSort(e.target.value)} className="h-10 rounded-md border border-[var(--line)] bg-[var(--panel)] px-3"><option value="createdAt">Newest</option><option value="name">Name</option><option value="size">Size</option></select><div className="flex rounded-md border border-[var(--line)] bg-[var(--panel)] p-1"><button onClick={()=>setView("list")} aria-label="List view" className={`grid size-8 place-items-center rounded ${view==="list"?"bg-[var(--bg)]":""}`}><List size={18}/></button><button onClick={()=>setView("grid")} aria-label="Grid view" className={`grid size-8 place-items-center rounded ${view==="grid"?"bg-[var(--bg)]":""}`}><Grid2X2 size={18}/></button></div></div>}
  {uploading.length>0&&<div className="mt-4 space-y-2">{uploading.map((u,i)=><div key={`${u.name}-${i}`} className="border border-[var(--line)] bg-[var(--panel)] p-3"><div className="flex justify-between text-sm"><span className="truncate">{u.name}</span><span>{u.progress}%</span></div><div className="mt-2 h-1.5 bg-[var(--line)]"><div className="h-full bg-emerald-600" style={{width:`${u.progress}%`}}/></div></div>)}</div>}
  {visibleFolders.length>0&&!query&&<div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{visibleFolders.map(folder=><button key={folder.id} onClick={()=>{setFolderId(folder.id);setPage(1)}} className="flex items-center gap-3 rounded-md border border-[var(--line)] bg-[var(--panel)] p-3 text-left hover:border-emerald-600"><Folder className="text-amber-500" fill="currentColor" size={22}/><span className="truncate text-sm font-medium">{folder.name}</span></button>)}</div>}
  <div className="mt-6">{loading?<div className="grid min-h-56 place-items-center"><Loader2 className="animate-spin text-[var(--muted)]"/></div>:files.length===0?<Empty onUpload={()=>input.current?.click()}/>:view==="grid"?<div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">{files.map(f=><FileCard key={f.id} file={f} download={download} remove={setDeleting}/>)}</div>:<FileList files={files} download={download} remove={setDeleting}/>}</div>
  {!dashboard&&pages>1&&<div className="mt-6 flex items-center justify-end gap-3"><button disabled={page===1} onClick={()=>setPage(p=>p-1)} aria-label="Previous page" className="grid size-9 place-items-center rounded-md border border-[var(--line)] disabled:opacity-40"><ChevronLeft/></button><span className="text-sm text-[var(--muted)]">Page {page} of {pages}</span><button disabled={page===pages} onClick={()=>setPage(p=>p+1)} aria-label="Next page" className="grid size-9 place-items-center rounded-md border border-[var(--line)] disabled:opacity-40"><ChevronRight/></button></div>}
  {drag&&<div onDragLeave={()=>setDrag(false)} className="fixed inset-0 z-50 grid place-items-center border-4 border-dashed border-emerald-500 bg-emerald-950/80 text-white"><div className="text-center"><Upload className="mx-auto" size={48}/><p className="mt-4 text-xl font-semibold">Drop files to upload</p></div></div>}
  {deleting&&<Modal close={()=>setDeleting(null)}><h2 className="text-xl font-semibold">Delete &quot;{deleting.originalName}&quot;?</h2><p className="mt-3 text-sm text-[var(--muted)]">This action cannot be undone.</p><div className="mt-7 flex justify-end gap-3"><button onClick={()=>setDeleting(null)} className="h-10 rounded-md border border-[var(--line)] px-4">Cancel</button><button onClick={remove} className="h-10 rounded-md bg-red-600 px-4 font-semibold text-white">Delete</button></div></Modal>}
  {newFolder&&<Modal close={()=>setNewFolder(false)}><h2 className="text-xl font-semibold">New folder</h2><form onSubmit={createFolder}><input autoFocus name="name" maxLength={100} required placeholder="Folder name" className="mt-5 h-11 w-full rounded-md border border-[var(--line)] bg-[var(--bg)] px-3"/><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>setNewFolder(false)} className="h-10 rounded-md border border-[var(--line)] px-4">Cancel</button><button className="h-10 rounded-md bg-emerald-700 px-4 font-semibold text-white">Create</button></div></form></Modal>}
 </section>
}
function Icon({type,size=22}:{type:string;size?:number}){if(type.startsWith("image/"))return <ImageIcon size={size}/>;if(type.startsWith("video/"))return <Video size={size}/>;if(type.startsWith("audio/"))return <Music size={size}/>;if(type.includes("zip")||type.includes("gzip"))return <Archive size={size}/>;if(type.includes("pdf")||type.startsWith("text/"))return <FileText size={size}/>;return <FileIcon size={size}/>}
function FileList({files,download,remove}:{files:CloudFile[];download:(f:CloudFile)=>void;remove:(f:CloudFile)=>void}){return <div className="overflow-x-auto border-y border-[var(--line)]"><table className="w-full min-w-[700px] text-left"><thead className="text-xs uppercase text-[var(--muted)]"><tr><th className="px-3 py-3 font-medium">Name</th><th className="px-3 py-3 font-medium">Folder</th><th className="px-3 py-3 font-medium">Size</th><th className="px-3 py-3 font-medium">Uploaded</th><th className="w-24"><span className="sr-only">Actions</span></th></tr></thead><tbody>{files.map(f=><tr key={f.id} className="border-t border-[var(--line)] hover:bg-[var(--panel)]"><td className="px-3 py-3"><Link href={`/files/${f.id}`} className="flex items-center gap-3 font-medium"><span className="text-emerald-600"><Icon type={f.mimeType}/></span><span className="max-w-[300px] truncate">{f.originalName}</span></Link></td><td className="px-3 text-sm text-[var(--muted)]">{f.folder.name}</td><td className="px-3 text-sm text-[var(--muted)]">{formatBytes(f.size)}</td><td className="px-3 text-sm text-[var(--muted)]">{new Date(f.createdAt).toLocaleDateString()}</td><td><div className="flex"><button onClick={()=>download(f)} className="grid size-9 place-items-center" aria-label={`Download ${f.originalName}`}><Download size={18}/></button><button onClick={()=>remove(f)} className="grid size-9 place-items-center text-red-600" aria-label={`Delete ${f.originalName}`}><Trash2 size={18}/></button></div></td></tr>)}</tbody></table></div>}
function FileCard({file,download,remove}:{file:CloudFile;download:(f:CloudFile)=>void;remove:(f:CloudFile)=>void}){return <article className="rounded-md border border-[var(--line)] bg-[var(--panel)] p-3"><Link href={`/files/${file.id}`} className="grid aspect-[4/3] place-items-center rounded bg-[var(--bg)] text-emerald-600"><Icon type={file.mimeType} size={42}/></Link><div className="mt-3 flex items-center justify-between gap-2"><div className="min-w-0"><p className="truncate text-sm font-medium">{file.originalName}</p><p className="mt-1 text-xs text-[var(--muted)]">{formatBytes(file.size)}</p></div><div className="flex"><button onClick={()=>download(file)} aria-label="Download" className="grid size-8 place-items-center"><Download size={17}/></button><button onClick={()=>remove(file)} aria-label="Delete" className="grid size-8 place-items-center text-red-600"><Trash2 size={17}/></button></div></div></article>}
function Empty({onUpload}:{onUpload:()=>void}){return <div className="grid min-h-72 place-items-center border-y border-dashed border-[var(--line)] text-center"><div><FileIcon className="mx-auto text-[var(--muted)]" size={40}/><h2 className="mt-4 font-semibold">No files here</h2><p className="mt-2 text-sm text-[var(--muted)]">Upload a file or drag it into this window.</p><button onClick={onUpload} className="mt-5 rounded-md bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Choose files</button></div></div>}
function Modal({children,close}:{children:React.ReactNode;close:()=>void}){return <div role="dialog" aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><button onClick={close} className="absolute inset-0" aria-label="Close dialog"/><div className="relative w-full max-w-md rounded-md bg-[var(--panel)] p-6 shadow-xl"><button onClick={close} className="absolute right-4 top-4" aria-label="Close"><X size={20}/></button>{children}</div></div>}
