"use client";
import { Archive, Check, ChevronLeft, ChevronRight, Copy, Download, File as FileIcon, FileText, Folder, FolderPlus, Grid2X2, Image as ImageIcon, Link2, List, Loader2, Music, Search, Share2, Trash2, Upload, Video, X } from "lucide-react";
import Link from "next/link";
import { ChangeEvent, DragEvent, useCallback, useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import { api, API_URL, formatBytes, uploadFile } from "@/lib/api";

type CloudFile = { id: string; originalName: string; mimeType: string; size: string; createdAt: string; folder: { id: string; name: string } };
type CloudFolder = { id: string; name: string; parentId: string | null; isRoot: boolean };
type Uploading = { name: string; progress: number };
type FileShare = { id: string; token?: string; expiresAt: string | null; maxDownloads: number | null; downloadCount: number; revokedAt?: string | null; createdAt: string };

export function FileManager({ dashboard = false }: { dashboard?: boolean }) {
  const input = useRef<HTMLInputElement>(null);
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const [files, setFiles] = useState<CloudFile[]>([]), [folders, setFolders] = useState<CloudFolder[]>([]), [folderId, setFolderId] = useState(""), [loading, setLoading] = useState(true), [view, setView] = useState<"list" | "grid">("list"), [search, setSearch] = useState(""), [query, setQuery] = useState(""), [type, setType] = useState("all"), [sort, setSort] = useState("createdAt"), [page, setPage] = useState(1), [pages, setPages] = useState(1), [drag, setDrag] = useState(false), [uploading, setUploading] = useState<Uploading[]>([]), [deleting, setDeleting] = useState<CloudFile | null>(null), [newFolder, setNewFolder] = useState(false), [sharing, setSharing] = useState<CloudFile | null>(null), [shares, setShares] = useState<FileShare[]>([]), [shareExpiration, setShareExpiration] = useState("never"), [shareMaxDownloads, setShareMaxDownloads] = useState(""), [shareResult, setShareResult] = useState<FileShare | null>(null), [shareLoading, setShareLoading] = useState(false), [copied, setCopied] = useState(false);
  const loadFolders = useCallback(async () => { const response = await api<{ folders: CloudFolder[] }>("/folders"); setFolders(response.folders); if (!folderId) { const root = response.folders.find((folder) => folder.isRoot); if (root) setFolderId(root.id); } }, [folderId]);
  const loadFiles = useCallback(async () => { if (!folderId) return; setLoading(true); try { const params = new URLSearchParams({ folderId, search: query, type, sort, order: sort === "name" ? "asc" : "desc", page: String(page), limit: dashboard ? "6" : "30" }); const response = await api<{ files: CloudFile[]; pagination: { pages: number } }>(`/files?${params}`); setFiles(response.files); setPages(response.pagination.pages || 1); } finally { setLoading(false); } }, [folderId, query, type, sort, page, dashboard]);
  useEffect(() => { loadFolders().catch((error) => toast.error(error.message)); }, [loadFolders]);
  useEffect(() => { loadFiles().catch((error) => toast.error(error.message)); }, [loadFiles]);
  useEffect(() => { if (timer.current) clearTimeout(timer.current); timer.current = setTimeout(() => { setQuery(search); setPage(1); }, 300); return () => { if (timer.current) clearTimeout(timer.current); }; }, [search]);
  async function upload(list: FileList | File[]) { if (!folderId) return; for (const file of Array.from(list)) { setUploading((value) => [...value, { name: file.name, progress: 0 }]); try { await uploadFile(folderId, file, (progress) => setUploading((value) => value.map((item) => item.name === file.name ? { ...item, progress } : item))); toast.success(`${file.name} uploaded`); } catch (error) { toast.error(error instanceof Error ? error.message : "Upload failed"); } finally { setUploading((value) => value.filter((item) => item.name !== file.name)); } } loadFiles(); }
  async function download(file: CloudFile) { try { window.location.assign(`${API_URL}/files/${file.id}/download`); } catch (error) { toast.error(error instanceof Error ? error.message : "Download failed"); } }
  async function remove() { if (!deleting) return; try { await api(`/files/${deleting.id}`, { method: "DELETE" }); toast.success("File deleted"); setDeleting(null); loadFiles(); } catch (error) { toast.error(error instanceof Error ? error.message : "Delete failed"); } }
  async function createFolder(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await api("/folders", { method: "POST", body: JSON.stringify({ name: form.get("name"), parentId: folderId }) }); setNewFolder(false); loadFolders(); toast.success("Folder created"); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not create folder"); } }
  async function openShare(file: CloudFile) { setSharing(file); setShareResult(null); setCopied(false); setShareExpiration("never"); setShareMaxDownloads(""); try { const response = await api<{ shares: FileShare[] }>(`/files/${file.id}/shares`); setShares(response.shares); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not load share links"); } }
  async function createShare(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!sharing) return; setShareLoading(true); try { const response = await api<{ share: FileShare }>(`/files/${sharing.id}/shares`, { method: "POST", body: JSON.stringify({ expiration: shareExpiration, maxDownloads: shareMaxDownloads ? Number(shareMaxDownloads) : null }) }); setShareResult(response.share); setShares((current) => [response.share, ...current]); toast.success("Share link created"); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not create share link"); } finally { setShareLoading(false); } }
  async function revokeShare(shareId: string) { try { await api(`/shares/${shareId}`, { method: "DELETE" }); setShares((current) => current.map((share) => share.id === shareId ? { ...share, revokedAt: new Date().toISOString() } : share)); toast.success("Share link revoked"); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not revoke share link"); } }
  async function copyShare() { if (!shareResult?.token) return; await navigator.clipboard.writeText(`${window.location.origin}/share/${shareResult.token}`); setCopied(true); toast.success("Link copied"); }
  function drop(event: DragEvent) { event.preventDefault(); setDrag(false); if (event.dataTransfer.files.length) upload(event.dataTransfer.files); }
  const visibleFolders = folders.filter((folder) => folder.parentId === folderId);
  const currentFolder = folders.find((folder) => folder.id === folderId)?.name ?? "My files";

  return <section onDragEnter={(event) => { event.preventDefault(); setDrag(true); }} onDragOver={(event) => event.preventDefault()} onDrop={drop}>
    <div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="cyber-kicker">{dashboard ? "Recent files" : "File workspace"}</p><h1 className={`${dashboard ? "text-xl" : "text-2xl"} mt-1 font-bold tracking-tight`}>{currentFolder}</h1><p className="mt-1 text-sm text-[var(--muted)]">{dashboard ? "Your latest additions, ready when you are." : "Organize and access everything in your private cloud."}</p></div><div className="flex gap-2"><button onClick={() => setNewFolder(true)} className="icon-button flex h-11 items-center gap-2 px-3 text-xs font-bold"><FolderPlus size={17} /><span className="hidden sm:inline">New folder</span></button><button onClick={() => input.current?.click()} className="cyber-button flex h-11 items-center gap-2 px-4 text-xs font-bold"><Upload size={17} /> Upload files</button><input ref={input} hidden type="file" multiple onChange={(event: ChangeEvent<HTMLInputElement>) => event.target.files && upload(event.target.files)} /></div></div>
    {!dashboard && <div className="cyber-panel mt-6 flex flex-col gap-3 p-3 sm:flex-row"><label className="relative min-w-0 flex-1"><Search className="absolute left-3 top-3 text-[var(--muted)]" size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search your files" className="cyber-input h-11 w-full pl-10 pr-3 text-sm" /></label><div className="flex gap-2"><select aria-label="File type" value={type} onChange={(event) => { setType(event.target.value); setPage(1); }} className="cyber-input h-11 min-w-0 flex-1 px-3 text-xs sm:w-36"><option value="all">All types</option><option value="image">Images</option><option value="video">Videos</option><option value="audio">Audio</option><option value="document">Documents</option><option value="archive">Archives</option></select><select aria-label="Sort files" value={sort} onChange={(event) => setSort(event.target.value)} className="cyber-input h-11 min-w-0 flex-1 px-3 text-xs sm:w-32"><option value="createdAt">Newest</option><option value="name">Name</option><option value="size">Size</option></select><div className="flex rounded-[10px] border border-[var(--line)] p-1"><button onClick={() => setView("list")} aria-label="List view" className={`icon-button size-8 border-0 ${view === "list" ? "bg-[var(--glow)] text-[var(--accent)]" : ""}`}><List size={17} /></button><button onClick={() => setView("grid")} aria-label="Grid view" className={`icon-button size-8 border-0 ${view === "grid" ? "bg-[var(--glow)] text-[var(--accent)]" : ""}`}><Grid2X2 size={17} /></button></div></div></div>}
    {uploading.length > 0 && <div className="mt-4 space-y-2">{uploading.map((item, index) => <div key={`${item.name}-${index}`} className="cyber-panel p-4"><div className="flex items-center justify-between gap-4 text-sm"><span className="truncate font-semibold">Uploading {item.name}</span><span className="shrink-0 text-xs font-bold text-[var(--accent)]">{item.progress}%</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[var(--panel-2)]"><div className="h-full rounded-full bg-[var(--accent)] transition-all" style={{ width: `${item.progress}%` }} /></div></div>)}</div>}
    {visibleFolders.length > 0 && !query && <div className="mt-6 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">{visibleFolders.map((folder) => <button key={folder.id} onClick={() => { setFolderId(folder.id); setPage(1); }} className="cyber-panel flex items-center gap-3 p-4 text-left transition-transform hover:-translate-y-0.5 hover:border-[var(--accent)]"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[var(--glow)] text-[var(--accent)]"><Folder size={20} /></span><span className="min-w-0"><span className="block truncate text-sm font-bold">{folder.name}</span><span className="mt-1 block text-[11px] text-[var(--muted)]">Folder</span></span></button>)}</div>}
    <div className="mt-6">{loading ? <div className="cyber-panel grid min-h-56 place-items-center"><Loader2 className="animate-spin text-[var(--accent)]" /></div> : files.length === 0 ? <Empty onUpload={() => input.current?.click()} /> : view === "grid" ? <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{files.map((file) => <FileCard key={file.id} file={file} download={download} remove={setDeleting} share={openShare} />)}</div> : <FileList files={files} download={download} remove={setDeleting} share={openShare} />}</div>
    {!dashboard && pages > 1 && <div className="mt-5 flex items-center justify-between gap-3"><span className="text-xs text-[var(--muted)]">Page {page} of {pages}</span><div className="flex gap-2"><button disabled={page === 1} onClick={() => setPage((value) => value - 1)} aria-label="Previous page" className="icon-button size-10 disabled:opacity-40"><ChevronLeft size={18} /></button><button disabled={page === pages} onClick={() => setPage((value) => value + 1)} aria-label="Next page" className="icon-button size-10 disabled:opacity-40"><ChevronRight size={18} /></button></div></div>}
    {drag && <div onDragLeave={() => setDrag(false)} className="fixed inset-0 z-50 grid place-items-center border-4 border-dashed border-[var(--accent)] bg-[#18355f]/90 p-6 text-white"><div className="text-center"><span className="mx-auto grid size-16 place-items-center rounded-2xl bg-white/10"><Upload size={32} /></span><p className="mt-5 text-2xl font-bold">Drop files to upload</p><p className="mt-2 text-sm text-blue-100/70">Release to add them to {currentFolder}</p></div></div>}
    {deleting && <Modal close={() => setDeleting(null)}><div className="mb-5 grid size-11 place-items-center rounded-xl bg-red-100 text-[var(--danger)] dark:bg-red-950/30"><Trash2 size={21} /></div><h2 className="text-xl font-bold">Delete this file?</h2><p className="mt-2 break-words text-sm text-[var(--muted)]">“{deleting.originalName}” will be permanently removed. This action cannot be undone.</p><div className="mt-7 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button onClick={() => setDeleting(null)} className="h-11 rounded-[10px] border border-[var(--line)] px-4 text-sm font-semibold">Cancel</button><button onClick={remove} className="h-11 rounded-[10px] bg-[var(--danger)] px-4 text-sm font-bold text-white">Delete file</button></div></Modal>}
    {newFolder && <Modal close={() => setNewFolder(false)}><h2 className="text-xl font-bold">Create a folder</h2><p className="mt-2 text-sm text-[var(--muted)]">Keep your workspace tidy with a new folder.</p><form onSubmit={createFolder}><input autoFocus name="name" maxLength={100} required placeholder="Folder name" className="cyber-input mt-5 h-12 w-full px-3 text-sm" /><div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" onClick={() => setNewFolder(false)} className="h-11 rounded-[10px] border border-[var(--line)] px-4 text-sm font-semibold">Cancel</button><button className="cyber-button h-11 px-5 text-sm font-bold">Create folder</button></div></form></Modal>}
    {sharing && <Modal close={() => setSharing(null)}><div className="mb-5 flex size-11 items-center justify-center rounded-xl bg-[var(--glow)] text-[var(--accent)]"><Share2 size={21} /></div><h2 className="text-xl font-bold">Share {sharing.originalName}</h2><p className="mt-2 text-sm text-[var(--muted)]">Anyone with the link can download this file while it is active.</p>{shareResult?.token && <div className="mt-5 rounded-xl border border-[var(--accent)] bg-[var(--glow)] p-3"><p className="text-[11px] font-bold text-[var(--accent)]">New share link</p><div className="mt-2 flex items-center gap-2"><input readOnly value={`${window.location.origin}/share/${shareResult.token}`} className="cyber-input h-10 min-w-0 flex-1 px-2 text-xs" /><button onClick={copyShare} className="icon-button size-10 shrink-0" aria-label="Copy share link">{copied ? <Check size={17} /> : <Copy size={17} />}</button></div></div>}<form onSubmit={createShare} className="mt-5 space-y-4"><div className="grid gap-3 sm:grid-cols-2"><label className="block"><span className="mb-2 block text-xs font-semibold">Expires</span><select value={shareExpiration} onChange={(event) => setShareExpiration(event.target.value)} className="cyber-input h-11 w-full px-3 text-sm"><option value="1h">In 1 hour</option><option value="1d">In 1 day</option><option value="7d">In 7 days</option><option value="never">Never</option></select></label><label className="block"><span className="mb-2 block text-xs font-semibold">Download limit</span><input value={shareMaxDownloads} onChange={(event) => setShareMaxDownloads(event.target.value.replace(/[^0-9]/g, ""))} inputMode="numeric" min="1" max="10000" placeholder="Unlimited" className="cyber-input h-11 w-full px-3 text-sm" /></label></div><button disabled={shareLoading} className="cyber-button flex h-11 w-full items-center justify-center gap-2 text-sm font-bold"><Link2 size={17} />{shareLoading ? "Creating..." : "Create new link"}</button></form>{shares.length > 0 && <div className="mt-7 border-t border-[var(--line)] pt-5"><p className="text-xs font-bold">Share links</p><div className="mt-3 space-y-2">{shares.map((share) => <div key={share.id} className="flex items-center justify-between gap-3 rounded-lg border border-[var(--line)] px-3 py-2.5"><div className="min-w-0"><p className="text-xs font-semibold">{share.revokedAt ? "Revoked" : share.expiresAt && new Date(share.expiresAt) < new Date() ? "Expired" : "Active"}</p><p className="mt-1 text-[10px] text-[var(--muted)]">{share.downloadCount}{share.maxDownloads ? ` / ${share.maxDownloads}` : ""} downloads</p></div>{!share.revokedAt && <button onClick={() => revokeShare(share.id)} className="shrink-0 text-[11px] font-bold text-[var(--danger)] hover:underline">Revoke</button>}</div>)}</div></div>}</Modal>}
  </section>;
}

function Icon({ type, size = 22 }: { type: string; size?: number }) { if (type.startsWith("image/")) return <ImageIcon size={size} />; if (type.startsWith("video/")) return <Video size={size} />; if (type.startsWith("audio/")) return <Music size={size} />; if (type.includes("zip") || type.includes("gzip")) return <Archive size={size} />; if (type.includes("pdf") || type.startsWith("text/")) return <FileText size={size} />; return <FileIcon size={size} />; }
function FileList({ files, download, remove, share }: { files: CloudFile[]; download: (file: CloudFile) => void; remove: (file: CloudFile) => void; share: (file: CloudFile) => void }) { return <><div className="cyber-panel hidden overflow-hidden md:block"><table className="w-full text-left"><thead className="border-b border-[var(--line)] text-[10px] font-bold uppercase tracking-[.08em] text-[var(--muted)]"><tr><th className="px-5 py-3">Name</th><th className="px-3 py-3">Folder</th><th className="px-3 py-3">Size</th><th className="px-3 py-3">Added</th><th className="w-32" /></tr></thead><tbody>{files.map((file) => <tr key={file.id} className="border-b border-[var(--line)] last:border-0 hover:bg-[var(--glow)]"><td className="px-5 py-3"><Link href={`/files/${file.id}`} className="flex items-center gap-3 text-sm font-semibold"><span className="grid size-9 place-items-center rounded-lg bg-[var(--glow)] text-[var(--accent)]"><Icon type={file.mimeType} size={18} /></span><span className="max-w-[330px] truncate">{file.originalName}</span></Link></td><td className="px-3 text-xs text-[var(--muted)]">{file.folder.name}</td><td className="px-3 text-xs text-[var(--muted)]">{formatBytes(file.size)}</td><td className="px-3 text-xs text-[var(--muted)]">{new Date(file.createdAt).toLocaleDateString()}</td><td><div className="flex"><button onClick={() => share(file)} className="icon-button size-9 border-0 text-[var(--accent)]" aria-label={`Share ${file.originalName}`}><Share2 size={16} /></button><button onClick={() => download(file)} className="icon-button size-9 border-0" aria-label={`Download ${file.originalName}`}><Download size={16} /></button><button onClick={() => remove(file)} className="icon-button size-9 border-0 text-[var(--danger)]" aria-label={`Delete ${file.originalName}`}><Trash2 size={16} /></button></div></td></tr>)}</tbody></table></div><div className="space-y-2 md:hidden">{files.map((file) => <article key={file.id} className="cyber-panel flex items-center gap-3 p-3"><Link href={`/files/${file.id}`} className="flex min-w-0 flex-1 items-center gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-[var(--glow)] text-[var(--accent)]"><Icon type={file.mimeType} size={19} /></span><span className="min-w-0"><span className="block truncate text-sm font-semibold">{file.originalName}</span><span className="mt-1 block text-[11px] text-[var(--muted)]">{formatBytes(file.size)} · {file.folder.name}</span></span></Link><button onClick={() => share(file)} className="icon-button size-9 shrink-0 text-[var(--accent)]" aria-label={`Share ${file.originalName}`}><Share2 size={16} /></button><button onClick={() => download(file)} className="icon-button size-9 shrink-0" aria-label={`Download ${file.originalName}`}><Download size={16} /></button><button onClick={() => remove(file)} className="icon-button size-9 shrink-0 text-[var(--danger)]" aria-label={`Delete ${file.originalName}`}><Trash2 size={16} /></button></article>)}</div></>; }
function FileCard({ file, download, remove, share }: { file: CloudFile; download: (file: CloudFile) => void; remove: (file: CloudFile) => void; share: (file: CloudFile) => void }) { return <article className="cyber-panel p-3 transition-transform hover:-translate-y-0.5"><Link href={`/files/${file.id}`} className="grid aspect-[4/3] place-items-center rounded-xl border border-[var(--line)] bg-[var(--panel-2)] text-[var(--accent)]"><Icon type={file.mimeType} size={38} /></Link><div className="mt-3 flex items-center justify-between gap-2"><Link href={`/files/${file.id}`} className="min-w-0"><p className="truncate text-sm font-bold">{file.originalName}</p><p className="mt-1 text-[11px] text-[var(--muted)]">{formatBytes(file.size)}</p></Link><div className="flex shrink-0"><button onClick={() => share(file)} aria-label={`Share ${file.originalName}`} className="icon-button size-8 border-0 text-[var(--accent)]"><Share2 size={16} /></button><button onClick={() => download(file)} aria-label={`Download ${file.originalName}`} className="icon-button size-8 border-0 text-[var(--accent)]"><Download size={16} /></button><button onClick={() => remove(file)} aria-label={`Delete ${file.originalName}`} className="icon-button size-8 border-0 text-[var(--danger)]"><Trash2 size={16} /></button></div></div></article>; }
function Empty({ onUpload }: { onUpload: () => void }) { return <div className="cyber-panel grid min-h-72 place-items-center p-6 text-center"><div><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-[var(--glow)] text-[var(--accent)]"><FileIcon size={28} /></span><h2 className="mt-5 text-lg font-bold">No files here yet</h2><p className="mt-2 text-sm text-[var(--muted)]">Upload a file to start building your cloud.</p><button onClick={onUpload} className="cyber-button mt-5 px-4 py-2.5 text-sm font-bold">Choose files</button></div></div>; }
function Modal({ children, close }: { children: React.ReactNode; close: () => void }) { return <div role="dialog" aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4 backdrop-blur-sm"><button onClick={close} className="absolute inset-0" aria-label="Close dialog" /><div className="cyber-panel relative w-full max-w-md p-6 sm:p-7"><button onClick={close} className="icon-button absolute right-4 top-4 size-9 border-0" aria-label="Close"><X size={18} /></button>{children}</div></div>; }
