"use client";
import { ArrowLeft, Download, File as FileIcon, Loader2 } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { api, formatBytes } from "@/lib/api";
type Detail={id:string;originalName:string;mimeType:string;size:string;createdAt:string;updatedAt:string;folder:{name:string}};
export default function FileDetail(){const {id}=useParams<{id:string}>();const [file,setFile]=useState<Detail|null>(null);useEffect(()=>{api<{file:Detail}>(`/files/${id}`).then(r=>setFile(r.file)).catch(e=>toast.error(e.message))},[id]);async function download(){const r=await api<{url:string}>(`/files/${id}/download`);window.location.assign(r.url)}if(!file)return <div className="grid min-h-[60vh] place-items-center"><Loader2 className="animate-spin text-[var(--accent)]"/></div>;return <div className="mx-auto max-w-3xl"><Link href="/files" className="inline-flex items-center gap-2 text-[10px] text-[var(--muted)]"><ArrowLeft size={15}/>RETURN TO EXPLORER</Link><div className="cyber-panel mt-8 grid aspect-[16/7] place-items-center text-[var(--accent)]"><FileIcon size={58}/></div><div className="mt-7 flex flex-wrap items-start justify-between gap-4"><div><p className="cyber-kicker">OBJECT INSPECTOR</p><h1 className="mt-2 break-all text-xl font-semibold">{file.originalName}</h1><p className="mt-2 text-[10px] text-[var(--accent-2)]">{file.mimeType}</p></div><button onClick={()=>download().catch(e=>toast.error(e.message))} className="cyber-button flex h-10 items-center gap-2 px-4 text-[10px] font-bold"><Download size={17}/>PULL OBJECT</button></div><dl className="cyber-panel mt-8 grid grid-cols-2 gap-6 p-5 text-xs sm:grid-cols-4"><Info label="SIZE" value={formatBytes(file.size)}/><Info label="VOLUME" value={file.folder.name}/><Info label="UPLOADED" value={new Date(file.createdAt).toLocaleDateString()}/><Info label="MODIFIED" value={new Date(file.updatedAt).toLocaleDateString()}/></dl></div>}
function Info({label,value}:{label:string;value:string}){return <div><dt className="text-[var(--muted)]">{label}</dt><dd className="mt-1 truncate font-medium">{value}</dd></div>}
