"use client";
import { ArrowLeft, Download, File as FileIcon, Loader2, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { API_URL, api, formatBytes } from "@/lib/api";
type Detail={id:string;originalName:string;mimeType:string;size:string;createdAt:string;updatedAt:string;folder:{name:string}};
export default function FileDetail(){const {id}=useParams<{id:string}>();const [file,setFile]=useState<Detail|null>(null);useEffect(()=>{api<{file:Detail}>(`/files/${id}`).then(r=>setFile(r.file)).catch(e=>toast.error(e.message))},[id]);async function download(){window.location.assign(`${API_URL}/files/${id}/download`)}if(!file)return <div className="grid min-h-[60vh] place-items-center"><Loader2 className="animate-spin text-[var(--accent)]"/></div>;return <div className="mx-auto max-w-4xl"><Link href="/files" className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--muted)] hover:text-[var(--accent)]"><ArrowLeft size={16}/>Back to files</Link><div className="cyber-panel mt-6 grid aspect-[16/6] place-items-center bg-[var(--panel-2)] text-[var(--accent)]"><span className="grid size-20 place-items-center rounded-3xl bg-[var(--glow)]"><FileIcon size={42}/></span></div><div className="mt-7 flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex items-center gap-2 text-xs font-semibold text-[var(--accent-2)]"><ShieldCheck size={15}/> Stored securely</div><h1 className="mt-2 break-all text-2xl font-bold tracking-tight">{file.originalName}</h1><p className="mt-2 text-sm text-[var(--muted)]">{file.mimeType}</p></div><button onClick={()=>download().catch(e=>toast.error(e.message))} className="cyber-button flex h-11 shrink-0 items-center justify-center gap-2 px-5 text-sm font-bold"><Download size={17}/> Download</button></div><dl className="cyber-panel mt-8 grid grid-cols-2 gap-5 p-5 sm:grid-cols-4"><Info label="Size" value={formatBytes(file.size)}/><Info label="Folder" value={file.folder.name}/><Info label="Uploaded" value={new Date(file.createdAt).toLocaleDateString()}/><Info label="Modified" value={new Date(file.updatedAt).toLocaleDateString()}/></dl></div>}
function Info({label,value}:{label:string;value:string}){return <div><dt className="text-xs text-[var(--muted)]">{label}</dt><dd className="mt-1 truncate text-sm font-bold">{value}</dd></div>}
