"use client";
import { ArrowLeft, Download, File as FileIcon, Loader2 } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { api, formatBytes } from "@/lib/api";
type Detail={id:string;originalName:string;mimeType:string;size:string;createdAt:string;updatedAt:string;folder:{name:string}};
export default function FileDetail(){const {id}=useParams<{id:string}>();const [file,setFile]=useState<Detail|null>(null);useEffect(()=>{api<{file:Detail}>(`/files/${id}`).then(r=>setFile(r.file)).catch(e=>toast.error(e.message))},[id]);async function download(){const r=await api<{url:string}>(`/files/${id}/download`);window.location.assign(r.url)}if(!file)return <div className="grid min-h-[60vh] place-items-center"><Loader2 className="animate-spin"/></div>;return <div className="mx-auto max-w-3xl"><Link href="/files" className="inline-flex items-center gap-2 text-sm text-[var(--muted)]"><ArrowLeft size={17}/>Back to files</Link><div className="mt-8 grid aspect-[16/7] place-items-center rounded-md border border-[var(--line)] bg-[var(--panel)] text-emerald-600"><FileIcon size={64}/></div><div className="mt-7 flex flex-wrap items-start justify-between gap-4"><div><h1 className="break-all text-2xl font-semibold">{file.originalName}</h1><p className="mt-2 text-sm text-[var(--muted)]">{file.mimeType}</p></div><button onClick={()=>download().catch(e=>toast.error(e.message))} className="flex h-10 items-center gap-2 rounded-md bg-emerald-700 px-4 font-semibold text-white"><Download size={18}/>Download</button></div><dl className="mt-8 grid grid-cols-2 gap-6 border-y border-[var(--line)] py-6 text-sm sm:grid-cols-4"><Info label="Size" value={formatBytes(file.size)}/><Info label="Folder" value={file.folder.name}/><Info label="Uploaded" value={new Date(file.createdAt).toLocaleDateString()}/><Info label="Modified" value={new Date(file.updatedAt).toLocaleDateString()}/></dl></div>}
function Info({label,value}:{label:string;value:string}){return <div><dt className="text-[var(--muted)]">{label}</dt><dd className="mt-1 truncate font-medium">{value}</dd></div>}
