CREATE TYPE "UploadStatus" AS ENUM ('PENDING', 'COMPLETED', 'EXPIRED');
CREATE TABLE "User" ("id" TEXT PRIMARY KEY, "name" TEXT NOT NULL, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "storageLimit" BIGINT NOT NULL DEFAULT 10737418240, "storageUsed" BIGINT NOT NULL DEFAULT 0, "storageReserved" BIGINT NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Session" ("id" TEXT PRIMARY KEY, "tokenHash" TEXT NOT NULL, "userId" TEXT NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "lastUsedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Folder" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL, "parentId" TEXT, "name" TEXT NOT NULL, "isRoot" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "File" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL, "folderId" TEXT NOT NULL, "originalName" TEXT NOT NULL, "s3Key" TEXT NOT NULL, "mimeType" TEXT NOT NULL, "size" BIGINT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "UploadIntent" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL, "folderId" TEXT NOT NULL, "originalName" TEXT NOT NULL, "s3Key" TEXT NOT NULL, "mimeType" TEXT NOT NULL, "size" BIGINT NOT NULL, "status" "UploadStatus" NOT NULL DEFAULT 'PENDING', "expiresAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE INDEX "User_email_idx" ON "User"("email");
CREATE UNIQUE INDEX "Session_tokenHash_key" ON "Session"("tokenHash");
CREATE INDEX "Session_userId_idx" ON "Session"("userId");
CREATE INDEX "Session_expiresAt_idx" ON "Session"("expiresAt");
CREATE UNIQUE INDEX "Folder_userId_parentId_name_key" ON "Folder"("userId", "parentId", "name");
CREATE INDEX "Folder_userId_parentId_idx" ON "Folder"("userId", "parentId");
CREATE UNIQUE INDEX "File_s3Key_key" ON "File"("s3Key");
CREATE INDEX "File_userId_folderId_idx" ON "File"("userId", "folderId");
CREATE INDEX "File_userId_originalName_idx" ON "File"("userId", "originalName");
CREATE INDEX "File_userId_createdAt_idx" ON "File"("userId", "createdAt");
CREATE INDEX "File_userId_mimeType_idx" ON "File"("userId", "mimeType");
CREATE UNIQUE INDEX "UploadIntent_s3Key_key" ON "UploadIntent"("s3Key");
CREATE INDEX "UploadIntent_userId_status_idx" ON "UploadIntent"("userId", "status");
CREATE INDEX "UploadIntent_expiresAt_status_idx" ON "UploadIntent"("expiresAt", "status");
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "Folder" ADD CONSTRAINT "Folder_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "Folder" ADD CONSTRAINT "Folder_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "Folder"("id") ON DELETE CASCADE;
ALTER TABLE "File" ADD CONSTRAINT "File_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "File" ADD CONSTRAINT "File_folderId_fkey" FOREIGN KEY ("folderId") REFERENCES "Folder"("id") ON DELETE RESTRICT;
ALTER TABLE "UploadIntent" ADD CONSTRAINT "UploadIntent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
